### ISSUE TITLE
missing A.3X.IR24

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/metadata#120]
*This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685*
# Comment
There is no test for TG MD requirement 24, because this is claimed to be not testable.
It is not clear why the temporal reference system cannot be tested.
Also, the values for data of creation / revision / updated can be tested whether they conform to the ISO 8601 format (yyy-mm-dd).
# Proposed Change
Add a test case for this requirement.

**Comment by michellutz** [comment]
The IR states: "Each date shall refer to a temporal reference system and shall be expressed in a form compatible with that system. The default reference system shall be the Gregorian calendar, with dates expressed in accordance with ISO 8601."

The latter part is repeated in TG req 24. It is not clear what "default reference system" means in practice - that the date should be interpreted as being specified according to the Gregorian calendar, if no reference system is explicitly specified?

If that's our interpretation, the test could check whether either

- a reference system is specified in the metadata (I'm not sure however, whether this is possible - the CI_Date type does not foresee the specification of a ref system) and the date is consistent with that reference system, or
- if no reference system is specified, the date is consistent with ISO 8601.

But this would require a slight change in the TG to make this interpretation clear.

**Comment by PeterParslow** [comment]
ISO 19115 references ISO 19103 for the basic type Date. 19103 says that the principles are discussed in 19108, and the representation is described in 8601. ISO 8601 explicitly only provides representations for dates in the Gregorian calendar. ISO 19108 doesn't actually disallow using the Date type with another calendar, but does provide other types specifically for that (e.g. TM_CalDate).

Overall, I think it is impossible to express a date in ISO 19115 which is not in the Gregorian calendar. Therefore I believe the Metadata TG should explicitly state that when encoding INSPIRE metadata in accordance with ISO 19115/19139, the dates shall be Gregorian.

This is distinct from providing the Temporal Reference System, which describes the dates that appear in the dataset. In the same way that the bounding box is always WGS-84 even if the data itself isn't.

Well, that's my reading of the standards....

**Comment by cportele** [comment]
As long as no TM_Xxx classifier is used (ie only Date, DateTime), the calendar is always Gregorian. That leaves only the temporal extent as a metadata element that could have a different reference system. Since ISO 19108 specifies the Gregorian calendar as the default system ("If not specified, it is assumed to be an association to the Gregorian calendar and UTC") and GML (where the XML representations of the TM classifiers are specified) does this, too, I think that requriement 24 is basically covered by design and XML Schema validation. 

If we follow the wording of requriement 24 to the letter, then maybe the following could be tested: //gmd:extent/gmd:EX_Extent/gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent/gml:TimePeriod/gml:beginPosition[not(@frame) and not(fn:matches(.,'^[0-9]{4}\-[0-9]{2}-\[0-9]{2}(T.*)?'))]. Same for gml:endPosition.

This expression finds only time positions that do not have the @frame attribute (which means that the default reference system is used), but where the temporal information does not start with the pattern YYYY-MM-DD, optionally followed by time information.

**Comment by michellutz** [comment]
Resolution agreed at the [Comment Resolution web-conference](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10):

Change test case for requirement 24 as described in Clemens’ comment to enforce the YYYY-MM-DD pattern when the default reference system is used.
