### ISSUE TITLE
Vocabulary test should check the date if the thesaurus is GEMET - INSPIRE themes, version 1.0

### ISSUE THREAD

**Issue by heidivanparys** [inspire-eu-validation/metadata#130]
The vocabulary test should check all of the following when the title of the thesaurus is "GEMET - INSPIRE themes, version 1.0":

- date type is publication
- date is 2008-06-01

Argument: it is not an explicit requirement in the TG and is given as example in section 2.4.2. However, the INSPIRE spatial data theme is a crucial keyword, thus it is important that all the information is present, correct and preferably containing the same date type - and thus date - in all member states.

See also https://ies-svn.jrc.ec.europa.eu/issues/3101

**Comment by cportele** [comment]
While I understand this request, I do not see it covered by the Technical Guidance. I think the relevant requirement is 18:

> The thesaurusName identification shall include at least the title and a reference date (date of publication, date of last revision or of creation) of the originating controlled vocabulary.

I.e., there is no requirement to provide a publication date. Any of the three types of dates is ok.

In order to test valid dates for selected vocabularies, a list of vocabulary titles and publication dates would need to be published and maintained somewhere. I guess the registry would be the place for this.

I tag this issue for discussion by the MIG-T subgroup.

**Comment by michellutz** [comment]
I agree that the use of the date of publication for the INSPIRE themes is not explicitly required in the MD TG v1.3, but only included in the example. If we agree that it should be a requirement (as it is in the v2.0 - see TG Requirement C.15: metadata/2.0/req/common/keyword-originating-cv), we would either need to update the TG v1.3, or agree that the ATS should be more strict than the requirements in the text.

We may need to have a general discussion on this topic, since it seems to be a recurring case for the (often un-precise v1.3 of the MD TG).

**Comment by aquaglia** [comment]
OK, but I do not think it is just  MD TG v1.3 to blame. TG MD 2.0.1 makes
it actually even worse with an explicit note:

*(24) Attribute codeList shall have value
"http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode
<http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode>"
and the attribute codeListValue value "publication". *

**Comment by AntoRot** [comment]
In addition, in the MD TG v1.3 the specific title of the thesaurus is not even explicitly required, as in the v2.0  - see TG Requirement 1.4: metadata/2.0/req/datasets-and-series/inspire-theme-keyword.
Furthermore, the TG requirement C.15 in MD TG v2.0 refers explicitly to the publication date of publication; indeed it reads as follows "The **publication date** of the vocabulary shall be given using the gmd:date/gmd:CI_Date/gmd:date/gco:Date and gmd:dateType/gmd:CI_DateTypeCode elements". The footnote only gives the implementation.  In case of a possible revision of the TG 2.0 the footnote could be added in the text  of the requirement.
So, since the TG v2.0 gives more specific requirements, I agree on the second option (more strict ATS) without updating the TG v.1.3.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-02-15] Even if the requirement in v1.3 of the TG is not requiring the date to be the date of publication, the given date and title should be correct with respect to the given controlled vocabulary. For the "GEMET - INSPIRE themes, version 1.0" (https://www.eionet.europa.eu/gemet/en/inspire-themes/), it should therefore be "2008-06-01" (date of publication). This should be clarified in a corrigendum for v1.3, and the ATS and ETS should be updated accordingly.

**Comment by michellutz** [comment]
[2017.4 meeting 2018-03-16] The conclusions from the previous meeting are confirmed. The issue should be closed and 3 new issues for ATS, ETS and TG changes should be created.
