### ISSUE TITLE
XML namespaces prefixes

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/metadata#95]
*This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685*
# Comment
The list is not complete (missing srv, gmx, and probably others)
# Proposed Change
Please complete

**Comment by jensscheerlinck** [comment]
# Proposed Resolution

Add the following namespaces to the list of namespace prefixes:
-gml http://www.opengis.net/gml/3.2
- srv http://www.isotc211.org/2005/srv/ -> This link appears to be currently broken, no alternative could be found
- gmx http://www.isotc211.org/2005/gmx/

**Comment by PeterParslow** [comment]
The absence of an official XSD set for the http://www.isotc211.org/2005/srv/ namespace is an ongoing problem. In the UK we were recommending one published by IGN, but they have quite reasonably asked us to stop doing that. We have asked JRC to look into hosting a set to be used across INSPIRE.
ISO TC211 are very unlikely to, because they have revised ISO 19119 since the version that we depend on (which didn't have the XML encoding as part of the standard). The new version has its XML included alongside the revised 19115, which we are (quite reasonably) not adopting yet.
I would take this opportunity to ask JRC again - at least as part of this validator development, but preferable with wider applicability, so that national & domain editors can make sure the schemaLocation in the metadata instances is set to a useful URL.

**Comment by aquaglia** [comment]
We should understand why EDEN withdrew the online schemas and whether the same reasons would apply for the JRC.

As we know, the only online schemas for srv are here:
http://schemas.opengis.net/iso/19139/20060504/srv/

We should consider that it is OGC which is publishing:
http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd
and that references the 2006 schemas.

We should also consider that some Member States, like UK, serve metadata using 2007 schemas through CSW 2.0.2 services claiming ISO AP 1.0 compliance.


http://schemas.opengis.net/iso/

**Comment by pvgenuchten** [comment]
it seems the suggested version of the schema doesn't include the gmx namespace, does this mean we can not use gmx:anchor in any inspire metadata?

**Comment by PeterParslow** [comment]
The way we solve that is to include a gmx.xsd. The gmx.xsd then includes gmd stuff & so on. This is "only" about where to find the rules for srv.

**Comment by jensscheerlinck** [comment]
Discussed during the MIWP-5 meeting:
A change request should be formulated to TG V1.3 because there is no clear requirement.

Also, regarding the SRV namespace, @PeterParslow is going to take this issue forward.
One current proposal is to: create consistent set of schemas (using GitHub) for JRC to host
**pro**: clear solution
**con**: yet another schema in the srv namespace and endorsement from all Member States required.
